### ISSUE TITLE
KTH results

### ISSUE THREAD

**Issue by Mareeta26** [yangguobei/TCTN-pytorch#3]
Thanks for the repo!
Is the KTH dataset used the same as given in [PredRNN V2](https://github.com/thuml/predrnn-pytorch/blob/master/core/data_provider/kth_action.py)?
I couldn't get the same results presented in the paper. It would be helpful if you could share the pre trained model for KTH or let me know if there is anything else I need to keep in mind while training?

Thank you!

**Comment by fanshuhuangjia** [comment]
> Thanks for the repo! Is the KTH dataset used the same as given in [PredRNN V2](https://github.com/thuml/predrnn-pytorch/blob/master/core/data_provider/kth_action.py)? I couldn't get the same results presented in the paper. It would be helpful if you could share the pre trained model for KTH or let me know if there is anything else I need to keep in mind while training?
> 
> Thank you!

The resolution of KTH in this paper is 64x64   (each frame is resized to 64×64)
